trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  displayName: "Terraform Init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    backendServiceArm: 'azureportal'
    backendAzureRmResourceGroupName: 'Jyoti_rg_centralIndia'
    backendAzureRmStorageAccountName: 'terraformtest12346'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.terraform.tfstate'

- task: TerraformTaskV4@4
  displayName: "Terraform Validate"
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'

- task: TerraformTaskV4@4
  displayName: "Terraform FMT"
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    customCommand: 'fmt'
    outputTo: 'console'
    environmentServiceNameAzureRM: 'azureportal'

- task: tfsec@1
  displayName: "Security Scan"
  inputs:
    version: 'v1.26.0'
    debug: true
    dir: '$(System.DefaultWorkingDirectory)'

- task: TerraformTaskV4@4
  displayName: "Terraform Plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    environmentServiceNameAzureRM: 'azureportal'



- task: TerraformTaskV4@4
  displayName: "Terraform Apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    environmentServiceNameAzureRM: 'azureportal'