trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    backendServiceArm: 'azureportal'
    backendAzureRmResourceGroupName: 'Jyoti_rg_centralIndia'
    backendAzureRmStorageAccountName: 'terraformtest12346'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    customCommand: 'fmt'
    outputTo: 'console'
    environmentServiceNameAzureRM: 'azureportal'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    environmentServiceNameAzureRM: 'azureportal'



- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    environmentServiceNameAzureRM: 'azureportal'